# Generated by Django 5.1 on 2024-08-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('niveau', models.IntegerField(default=1)),
                ('points_de_vie', models.IntegerField()),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('vitesse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('niveau', models.IntegerField(default=1)),
                ('heros', models.ManyToManyField(to='heros.hero')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('hero_joueur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_hero1', to='heros.hero')),
                ('hero_joueur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_hero2', to='heros.hero')),
                ('gagnant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_gagnes', to='heros.joueur')),
                ('joueur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_joueur1', to='heros.joueur')),
                ('joueur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_joueur2', to='heros.joueur')),
            ],
        ),
    ]
